


# Get All Voucher By Merchant
###
GET {{Host}}/api/v1/voucher/merchant-vouchers
Authorization: {{token}}


#  Create Voucher
###
POST {{Host}}/api/v1/voucher/ 
Content-Type: application/json
Authorization: {{token}}

{
  "amount": 50,
  "paymentMethod": "Credit Card",
  "status": "unpaid",
  "customFields": {
    "Applicant Name": "Javad Saeed",
    "Bill date": "2024-03-21",
    "Father Name": "Saeed Rehman",
    "Department": "University Institute of Radiological Sciences"
  }
}

# Delete Voucher
###
DELETE {{Host}}/api/v1/voucher/6565b22957050f937273d62c
Authorization: {{token}}