


# Get All Voucher By Merchant
###
GET {{Host}}/api/v1/voucher/merchant-vouchers
Authorization: {{token}}


#  Create Voucher
###
POST {{Host}}/api/v1/voucher/ 
Content-Type: application/json
Authorization: {{token}}

{
  "customFields": {
    "Applicant Name": "Javad Saeed",
    "Bill date": "2024-03-21",
    "Father Name": "Saeed Rehman",
    "Department": "University Institute of Radiological Sciences"
  }
}

# Delete Voucher
###
DELETE {{Host}}/api/v1/voucher/65dee438d99eceffdec4403e
Authorization: {{token}}

# Update voucher status
###
PUT {{Host}}/api/v1/onboarding/update-status/66265d58d9b9664f0e9fdee0
Content-Type: application/json
Authorization: {{token}}

{
  "status": "paid"
}